In [11]:
# 1. torch.nn.utils.rnn.pad_sequence - https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pad_sequence.html#torch-nn-utils-rnn-pad-sequence
# it pads up uneven rows, when the column numbers are the same and vice versa
import torch
from torch.nn.utils.rnn import pad_sequence

#exmaple 1

a = torch.ones(20, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
print(pad_sequence([a, b, c]).size())

torch.Size([22, 3, 300])


This function returns a Tensor of size T x B x * or B x T x * where T is the length of the longest sequence. This function assumes trailing dimensions and type of all the Tensors in sequences are same.

Parameters:
sequences (list[Tensor]) – list of variable length sequences.

batch_first (bool, optional) – output will be in B x T x * if True, or in T x B x * otherwise. Default: False.

padding_value (float, optional) – value for padded elements. Default: 0.

Returns:
Tensor of size T x B x * if batch_first is False. Tensor of size B x T x * otherwise

Return type:
Tensor

In [ ]:
# Example 2

# trace
torch.einsum('ii', torch.randn(4, 4))

# diagonal
torch.einsum('ii->i', torch.randn(4, 4))

# outer product
x = torch.randn(5)
y = torch.randn(4)
torch.einsum('i,j->ij', x, y)
# batch matrix multiplication
As = torch.randn(3, 2, 5)
Bs = torch.randn(3, 5, 4)
torch.einsum('bij,bjk->bik', As, Bs)
# with sublist format and ellipsis
torch.einsum(As, [..., 0, 1], Bs, [..., 1, 2], [..., 0, 2])
# batch permute
A = torch.randn(2, 3, 4, 5)
torch.einsum('...ij->...ji', A).shape
# equivalent to torch.nn.functional.bilinear
A = torch.randn(3, 5, 4)
l = torch.randn(2, 5)
r = torch.randn(2, 4)
torch.einsum('bn,anm,bm->ba', l, A, r)

In [91]:
# A = torch.randn(3, 5, 4)
torch.manual_seed(42)
l = torch.randn(2, 3)
r = torch.randn(4, 2)
# n = torch.einsum('bn,anm,bm ->ba', l, A, r)
l,r,l[...,-1:], r[:,1:]

(tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]]),
 tensor([[ 2.2082, -0.6380],
         [ 0.4617,  0.2674],
         [ 0.5349,  0.8094],
         [ 1.1103, -1.6898]]),
 tensor([[ 0.2345],
         [-0.1863]]),
 tensor([[-0.6380],
         [ 0.2674],
         [ 0.8094],
         [-1.6898]]))

In [89]:
torch.manual_seed(42)
x = torch.randn(1,4,4)
y = len(x.shape)

x, y

(tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055],
          [ 0.6784, -1.2345, -0.0431, -1.6047],
          [-0.7521,  1.6487, -0.3925, -1.4036],
          [-0.7279, -0.5594, -0.7688,  0.7624]]]),
 3)